/*
   STEP pulses are generated by the Servo timer (50 Hz).
   Each 20 ms frame contains a 1 ms HIGH (servo-style “1000 µs”).
   400 frames  → 400 steps  → ~2 motor revs (at 50 steps·s-¹ that’s 8 s).
*/

#include <Servo.h>

// ---- USER SETTINGS -------------------------------------------------
const byte STEP_PIN   = 11;   // STEP / PULSE
const byte DIR_PIN    = 8;    // DIR
const int  STEPS_TEST = 400;  // ≈ 2 rev on a 200-step motor
const int  PULSE_US   = 1000; // width of the HIGH portion (µs)      (≥544 µs) :contentReference[oaicite:1]{index=1}
const int  FRAME_MS   = 50;   // 50 Hz refresh (fixed in Servo lib)  :contentReference[oaicite:2]{index=2}
// --------------------------------------------------------------------

Servo pulse;                  // the Servo object is now a “pulse engine”

void setup() {
  pulse.attach(STEP_PIN);                 // start 50 Hz signalling
  pulse.writeMicroseconds(PULSE_US);      // HIGH-time per frame
  pinMode(DIR_PIN, OUTPUT);
  digitalWrite(DIR_PIN, LOW);
}

void loop() {
  // --- forward (DIR = LOW) ---
  digitalWrite(DIR_PIN, HIGH);
  runSteps(STEPS_TEST);
 // delay(1000);

  // --- reverse (DIR = HIGH) ---
  //digitalWrite(DIR_PIN, HIGH);
  //runSteps(STEPS_TEST);
  //delay(2000);
}

// counts frames → counts steps
void runSteps(int n) {
  for (int i = 0; i < n; ++i) {
    delay(FRAME_MS);           // wait for the next automatic servo frame
  }
}
